# Generated by Django 5.2.10 on 2026-01-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название маршрута')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('distance_km', models.FloatField(help_text='Заявленная длина', verbose_name='Дистанция (км)')),
                ('route_type', models.CharField(choices=[('WALK', 'Пешеходный'), ('BIKE', 'Велосипедный')], default='WALK', max_length=10, verbose_name='Тип')),
                ('gpx_file', models.FileField(upload_to='routes/gpx/', verbose_name='GPX файл')),
                ('geometry', models.JSONField(blank=True, editable=False, null=True, verbose_name='GeoJSON геометрия')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
                'ordering': ['-year', 'distance_km'],
            },
        ),
    ]
