# Generated by Django 5.2.10 on 2026-01-14 16:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={},
        ),
        migrations.RemoveField(
            model_name='route',
            name='distance_km',
        ),
        migrations.RemoveField(
            model_name='route',
            name='geometry',
        ),
        migrations.RemoveField(
            model_name='route',
            name='gpx_file',
        ),
        migrations.RemoveField(
            model_name='route',
            name='route_type',
        ),
        migrations.RemoveField(
            model_name='route',
            name='title',
        ),
        migrations.RemoveField(
            model_name='route',
            name='year',
        ),
        migrations.AddField(
            model_name='route',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата проведения'),
        ),
        migrations.AddField(
            model_name='route',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='route',
            name='distanceKm',
            field=models.FloatField(default=0.0, verbose_name='Дистанция (км)'),
        ),
        migrations.AddField(
            model_name='route',
            name='name',
            field=models.CharField(default='Новый маршрут', max_length=255, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='route',
            name='points',
            field=models.JSONField(blank=True, default=list, verbose_name='Координаты (трек)'),
        ),
        migrations.AddField(
            model_name='route',
            name='startLocation',
            field=models.JSONField(blank=True, default=dict, verbose_name='Место старта'),
        ),
        migrations.AddField(
            model_name='route',
            name='walkType',
            field=models.CharField(choices=[('walk', 'Пешая'), ('bike', 'Велосипедная')], default='walk', max_length=10, verbose_name='Тип прогулки'),
        ),
    ]
