# Generated by Django 5.2.10 on 2026-01-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_alter_route_options_remove_route_distance_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='endLocation',
            field=models.JSONField(blank=True, default=dict, verbose_name='Место финиша'),
        ),
    ]
