# Generated by Django 5.2.10 on 2026-01-15 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_route_endlocation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'Маршрут', 'verbose_name_plural': 'Маршруты'},
        ),
    ]
